PATH="/home/john/jf/latex-technical-nonfiction-book/bin:/home/john/jf/latex-technical-nonfiction-book/bin:/home/john/jf/latex-technical-nonfiction-book/bin:/home/john/Documents/CT/book/bin:/home/john/bin:/usr/local/texlive/2016/bin/x86_64-linux:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"
mkdir -p "./all_epub/logs"
mkdir -p "./all_epub/images"
mkdir -p "./all_epub/tex"
cp eBook.tex   "./all_epub"
cp "eBook.cfg" "./all_epub"
cp "book.bib" "./all_epub"
cp "tex4ht.env" "./all_epub"
cp -R ./images/* "./all_epub/images"
cp -R ./tex/*        "./all_epub/tex"
cp "setParameters.bash" "./all_epub"
rm 'setParameters.bash'
cp "BookParameters.tex" "./all_epub"
cd "./all_epub"
